[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  publish = "dist"
  port = 9002
  targetPort = 9002
  framework = "#custom"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--omit=dev"

[functions]
  node_bundler = "esbuild"

[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development"

[context.branch-deploy.environment]
  NODE_ENV = "development"
