[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  publish = "dist"
  port = 9002

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--omit=dev"

[functions]
  node_bundler = "esbuild"

[dev]
  framework = "#custom"
  targetPort = 9002
