[build]
  command = "npm install && npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--omit=dev"
  CI = "false"

[functions]
  node_bundler = "esbuild"
  external_node_modules = []

[context.production]
  command = "npm install --production && npm run build"
  [context.production.environment]
    NODE_ENV = "production"

[context.deploy-preview]
  command = "npm install && npm run build"
  [context.deploy-preview.environment]
    NODE_ENV = "development"

[context.branch-deploy]
  command = "npm install && npm run build"
  [context.branch-deploy.environment]
    NODE_ENV = "development"

[plugins]
  [plugins."@netlify/plugin-lighthouse"]
    skip = true
